const data = {
  products: [
    {
      name: 'All Start Shoes',
      slug: 'all-start',
      category: 'Shoes',
      image: '/images/166408C_D_107X1converse.jpg',
      price: 70,
      brand: 'Nike',
      raiting: 4.5,
      numReviews: 10,
      countInstock: 20,
      description: 'A popular Shoes',
    },
    {
      name: 'Fit Shoes',
      slug: 'fit',
      category: 'Shoes',
      image: '/images/adidas.jpg',
      price: 80,
      brand: 'Adidas',
      raiting: 4.2,
      numReviews: 10,
      countInstock: 20,
      description: 'A popular Shoes',
    },
    {
      name: 'Slim Shoes',
      slug: 'slim',
      category: 'Shoes',
      image: '/images/66387_BLK_Braymon.jpg',
      price: 20,
      brand: 'Raymon',
      raiting: 3.4,
      numReviews: 240,
      countInstock: 60,
      description: 'A popular shirt',
    },
    {
      name: 'KD Tray Shoes',
      slug: 'kd-tray',
      category: 'Shoes',
      image: '/images/CZ4166_006_P2jordan.jpg',
      price: 40,
      brand: 'Jordan',
      raiting: 3.5,
      numReviews: 10,
      countInstock: 24,
      description: 'A popular shirt',
    },
    {
      name: 'Senior Shoes',
      slug: 'senior',
      category: 'Shoes',
      image: '/images/CZ0907_006_P2jordan.jpg',
      price: 60,
      brand: 'Raymon',
      raiting: 2.5,
      numReviews: 20,
      countInstock: 24,
      description: 'A popular shirt',
    },
  ],
};

export default data;
